/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:47f30848-c1e5-4574-bf06-e10d683abc3d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_74cawTLuP",
    "aws_user_pools_web_client_id": "5ls3gj88nnleeeliq15ggjc7ep",
    "oauth": {
        "domain": "velpaauth-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/--/,exp://exp.host/@mateodelat/velpa/",
        "redirectSignOut": "exp://127.0.0.1:19000/--/,exp://exp.host/@mateodelat/velpa/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://dkw4y37lebcl5ipwdh3zmbl2c4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-swcawfepxnfn5bhbinnq3qylui",
    "aws_user_files_s3_bucket": "velpanewversion3d014069f75d4be1bc2875498e9be3dc193449-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
