/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:27777e6d-857e-4187-84b6-85a17891d320",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MLaD0VGx7",
    "aws_user_pools_web_client_id": "6kanfftqjuu7pgv7415or1hkl9",
    "oauth": {
        "domain": "velpaf3732cb1-f3732cb1-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "aws.cognito.signin.user.admin",
            "email",
            "openid",
            "phone",
            "profile"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/--/,exp://exp.host/@mateodelat/velpa/",
        "redirectSignOut": "exp://127.0.0.1:19000/--/,exp://exp.host/@mateodelat/velpa/",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_appsync_graphqlEndpoint": "https://tlpmf7idfvextlpbc4qrrmwgfy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3tpwvu3nobf35bk4mmx3m3gfnq",
    "aws_user_files_s3_bucket": "velpanewversion3d014069f75d4be1bc2875498e9be3dc193449-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
