/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://da53snwmh5cghpjxgvila7yeca.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ymgfb4dwgvh57omxgsujxtwnga",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://n30p07ig9k.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:b261f2b1-f83e-4334-93b4-968e61832ae5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZF17oghvX",
    "aws_user_pools_web_client_id": "4kl5uljljpanfk8tslcjr0k5i2",
    "oauth": {
        "domain": "velpa301c3a21-301c3a21-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/--/,exp://exp.host/@mateodelat/Velpa/,velpa://",
        "redirectSignOut": "exp://127.0.0.1:19000/--/,exp://exp.host/@mateodelat/Velpa/,velpa://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "velpa42e685acc3e9434897218e4adda8cb97194314-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
